M48
; DRILL file {KiCad 9.0.7} date 2026-04-09T10:52:08-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-09T10:52:08-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.540
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C4.300
%
G90
G05
T1
X109.877Y-55.85
X109.977Y-81.25
T2
X57.33Y-91.89
X78.33Y-91.89
T3
X58.09Y-40.15
X58.09Y-82.15
X150.09Y-40.15
X150.09Y-82.15
M30
